config/routes.rb
BibleJeopardy::Application.routes.draw do
  get "categories/index"
  get "categories/edit"
  get "categories/show"
  get "categories/new"
  
  get "scores/index"
  get "scores/edit"
  get "scores/show"
  get "scores/new"

  get "boards/index"
  get "boards/edit"
  get "boards/show"
  get "boards/new"
  get "practice" => "boards#random_practice" 

  get "clues/index"
  get "clues/edit"
  get "clues/show"
  get "clues/new"
  get "clues/import"
  post "clues/import"


  get "/admin/import-clues" => "admins#import_clues"
  devise_for :users
  devise_for :admins

  root :to => "static_pages#home"

  resources :clues do
    collection {post :import}
  end

  resources :boards


end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/board.rb
class Board < ActiveRecord::Base
  has_many :categorysets
  has_many :categories, through: :categorysets
  has_many :cluesets
  has_many :clues, through: :cluesets

  validates :name, presence: true
  

  def next
    unless Board.where("difficulty > ?", self.difficulty).empty?
        Board.where("difficulty > ?", self.difficulty).order("difficulty").first 
    else
        Board.where("difficulty < ?", self.difficulty).order("difficulty").first    
    end
  end

  def previous
    unless Board.where("difficulty < ?", self.difficulty).empty?
        Board.where("difficulty < ?", self.difficulty).order("difficulty").last
    else
        Board.where("difficulty > ?", self.difficulty).order("difficulty").last
    end
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :clues
  has_many :categorysets
  has_many :boards, through: :categorysets

  validates :name, presence: true
end

app/models/categoryset.rb
class Categoryset < ActiveRecord::Base
  belongs_to :category
  belongs_to :board
end

app/models/clue.rb
class Clue < ActiveRecord::Base
    has_and_belongs_to_many :categories
    has_many :cluesets
    has_many :boards, through: :cluesets

    validates :prompt, :response, :presence => true

    def dollar_value(board)
        return case
        when board.difficulty == 1
            self.difficulty * 10
        when board.difficulty == 2
            self.difficulty * 50
        when board.difficulty == 3
            self.difficulty * 100
        end
    end

    def self.import(file)
        puts "Importing #{file.inspect}"
        spreadsheet = open_spreadsheet(file)
        header = spreadsheet.row(1)
        (2..spreadsheet.last_row).each do |i|
            row = Hash[[header, spreadsheet.row(i)].transpose]
            unless row["Prompt"].blank? || row["Response"].blank? || row["Board"].blank?
                clue = find_by_id(row["Question ID"]) || new
                clue.prompt = row["Prompt"]
                clue.response = row["Response"]
                category = Category.find_or_create_by_name(row["Category"])
                clue.passage = [row["Book"],row["Chapter and Verse"]].join(" ")
                board = Board.find_or_create_by_name("Board "+row["Board"].to_i.to_s)
                board.difficulty = row["Board"].to_i
                board.save!
                case
                when row["Value"].to_i == 10 || row["Value"] == "10"
                    clue.difficulty = 1
                when row["Value"].to_i == 20 || row["Value"] == "20"
                    clue.difficulty = 2
                when row["Value"].to_i == 30 || row["Value"] == "30"
                    clue.difficulty = 3
                when row["Value"].to_i == 40 || row["Value"] == "40"
                    clue.difficulty = 4
                when row["Value"].to_i == 50 || row["Value"] == "50"
                    clue.difficulty = 5 if row["Board"] == "1" || row["Board"].to_i == 1
                    clue.difficulty = 1 if row["Board"] == "2" || row["Board"].to_i == 2
                when row["Value"].to_i == 100 || row["Value"] == "100"
                    clue.difficulty = 2 if row["Board"] == "2" || row["Board"].to_i == 2
                    clue.difficulty = 1 if row["Board"] == "3" || row["Board"].to_i == 3
                when row["Value"].to_i == 150 || row["Value"] == "150"
                    clue.difficulty = 3 if row["Board"] == "2" || row["Board"].to_i == 2
                when row["Value"].to_i == 200 || row["Value"] == "200"
                    clue.difficulty = 4 if row["Board"] == "2" || row["Board"].to_i == 2
                    clue.difficulty = 2 if row["Board"] == "3" || row["Board"].to_i == 3
                when row["Value"].to_i == 250 || row["Value"] == "250"
                    clue.difficulty = 5 if row["Board"] == "2" || row["Board"].to_i == 2
                when row["Value"].to_i == 300 || row["Value"] == "300"
                    clue.difficulty = 3
                when row["Value"].to_i == 400 || row["Value"] == "400"
                    clue.difficulty = 4
                when row["Value"].to_i == 500 || row["Value"] == "500"
                    clue.difficulty = 5
                end
                raise if clue.difficulty.nil?
                clue.save!
                clue.categories << category unless clue.categories.include?(category)
                board.clues << clue unless board.clues.include?(clue)
                board.categories << category unless board.categories.include?(category)
            end
        end
    end

    def self.open_spreadsheet(file)
        case File.extname(file.original_filename)
        when ".csv" then Roo::Csv.new(file.path, nil, :ignore)
        when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
        when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore)
        else raise "Unknown file type: #{file.original_filename}"
        end
    end
end

app/models/clueset.rb
class Clueset < ActiveRecord::Base
  belongs_to :clue
  belongs_to :board
end

app/models/score.rb
class Score < ActiveRecord::Base
  belongs_to :user
  belongs_to :board
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
    def index

    end

    def import_clues
        
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def index
  end

  def edit
  end

  def show
    unless Board.where(id: params[:id]).empty?
        @board = Board.find(params[:id]) 
    else
        redirect_to :root, notice: "Board not found"
    end
  end

  def new
  end

  def random_practice
    redirect_to Board.all.shuffle.first
  end

  private

  def boards_params
    params.require(:board).permit(:name, :difficulty)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
  end

  def edit
  end

  def show
  end

  def new
  end

  private

  def categories_params
  	params.require(:category).permit(:name)
  end
end

app/controllers/clues_controller.rb
class CluesController < ApplicationController
  def index
  end

  def edit
  end

  def show
  end

  def new
  end

  def import
    Clue.import(params[:file])
    redirect_to '/admin/import-clues', notice: "Clues Imported"
  end

  private

  def clues_params
    params.require(:clue).permit(:difficulty, :passage, :prompt, :response)
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  def index
  end

  def edit
  end

  def show
  end

  def new
  end

  private

  def scores_params
  	params.require(:score).permit(:value)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def home
        render layout: "narrow"
    end

    def about

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def parent_layout(layout)
        @view_flow.set(:layout, output_buffer)
        self.output_buffer = render(:file => "layouts/#{layout}")
    end
    def nav_link(link_text, link_path, force_active = false, link_class="")
        class_name = (force_active || current_page?(link_path)) ? 'active' : ''
        link_path << "?access_token=#{@access_token}" if @access_token
        content_tag(:li, class: class_name) do
            link_to link_text, link_path, class: link_class
        end
    end
end

app/views/admins/import_clues.html.erb
<h2>Import Clues</h2>
<%= form_tag import_clues_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Import" %>
<% end %>

app/views/admins/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/boards/_clue.html.erb
<div class="clue jbg" data-toggle="modal" data-target="#clue-<%= clue.id %>">
    <h2 class="value"><%=clue.dollar_value(@board)%></h2> 
</div>
<div class="modal fade" aria-hidden="true" id="clue-<%= clue.id%>">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h3><%= "Clue #{clue.id}"%></h3>
            </div>
            <div class="modal-body">
                <p class="prompt"><%= clue.prompt%></p>
            </div>
            <div class="modal-footer">
                <div class="slider">
                    <p class="button">Reveal Answer</p><p class="response hidden"><%= clue.response %></p>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/boards/edit.html.erb
<h1>Boards#edit</h1>
<p>Find me in app/views/boards/edit.html.erb</p>

app/views/boards/index.html.erb
<h1>Boards#index</h1>
<p>Find me in app/views/boards/index.html.erb</p>

app/views/boards/new.html.erb
<h1>Boards#new</h1>
<p>Find me in app/views/boards/new.html.erb</p>

app/views/boards/show.html.erb
<div class="row">
<h1 class="col-md-12">
  <div class="row">
    <div class="col-md-4">
      <%= @board.name %>  
    </div> 
    <div class="col-md-4 col-md-offset-4 board-direction">
    <%= link_to 'Previous Board', board_path(@board.previous), class: "btn btn-default" %>
    <%= link_to 'Next Board', board_path(@board.next), class: 'btn btn-default' %>
    </div>
  </div>  
</h1>
</div>
<div class="board">
<% @board.categories.uniq.each do |category| %>
<div class="category-column">
    <div class="category jbg">
        <h2><%=category.name %></h2>
    </div>
    <% cat_clues = category.clues.order("difficulty").select{|c| c.boards.include?(@board)}.uniq %>
    <% cat_clues.each do |clue| %>
    <%= render "boards/clue", clue: Clue.find(clue.id) %>
    <% end %>
</div>
<% end %>
</div>

app/views/categories/edit.html.erb
<h1>Categories#edit</h1>
<p>Find me in app/views/categories/edit.html.erb</p>

app/views/categories/index.html.erb
<h1>Categories#index</h1>
<p>Find me in app/views/categories/index.html.erb</p>

app/views/categories/new.html.erb
<h1>Categories#new</h1>
<p>Find me in app/views/categories/new.html.erb</p>

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>

app/views/clues/edit.html.erb
<h1>Clues#edit</h1>
<p>Find me in app/views/clues/edit.html.erb</p>

app/views/clues/index.html.erb
<h1>Clues#index</h1>
<p>Find me in app/views/clues/index.html.erb</p>

app/views/clues/new.html.erb
<h1>Clues#new</h1>
<p>Find me in app/views/clues/new.html.erb</p>

app/views/clues/show.html.erb
<h1>Clues#show</h1>
<p>Find me in app/views/clues/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? yield(:title) : "Bible Jeopardy" %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= render "shared/main_navigation" %>
    <% if notice %><p class="notice"><%= notice %></p><% end %>
    <% if alert %><p class="alert"<%= alert %></p><% end %>
    <div class="container">
        <%= yield %>
    </div>
</body>
</html>

app/views/layouts/base.html.erb
<div class="container">
    <%= yield %>
</div>

<% parent_layout 'application' %>

app/views/layouts/narrow.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? yield(:title) : "Bible Jeopardy" %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= render "shared/main_navigation" %>
    <div class="container">
        <% if notice %><p class="notice"><%= notice %></p><% end %>
        <% if alert %><p class="alert"<%= alert %></p><% end %>
    <%= yield %>
    </div>
</body>
</html>

app/views/scores/edit.html.erb
<h1>Scores#edit</h1>
<p>Find me in app/views/scores/edit.html.erb</p>

app/views/scores/index.html.erb
<h1>Scores#index</h1>
<p>Find me in app/views/scores/index.html.erb</p>

app/views/scores/new.html.erb
<h1>Scores#new</h1>
<p>Find me in app/views/scores/new.html.erb</p>

app/views/scores/show.html.erb
<h1>Scores#show</h1>
<p>Find me in app/views/scores/show.html.erb</p>

app/views/shared/_main_navigation.html.erb
<header>
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <%= link_to "BIBLE Jeopardy!", root_path, class: "navbar-brand" %>
            </div>
                <ul class="nav navbar-nav navbar-right">
                    <!--<%= nav_link "Play", '#' %>-->
                    <%= nav_link "Practice", '/practice', false %>
                    <!--<%= nav_link "About", "/about" %>-->
                    <% if user_signed_in? %>
                        <%= nav_link 'Logout', destroy_user_session_path, false, 'log-out' %> 
                    <% else %>
                        <%= nav_link 'Sign In', new_user_session_path, false, "sign-up" %>
                    <% end %>
                </ul>
        </div>
    </div>
</header>

app/views/static_pages/home.html.erb
<div class="jumbotron">
  <h1>Are you ready for Bible Jeopardy?</h1>
  <p class="lead">Prepare to challenge your friends, your enemies, and your church leaders to a <del>friendly</del> game of Bible Jeopardy.</p>
  <a class="btn btn-large btn-success" href="/practice">Start Practice</a>
</div>

<hr>

<div class="footer">
  <p>© 2013-<%= Time.now.strftime('%Y') %> Mike Wyatt Design </p>
</div>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>